/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InterfazR;

import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.BorderFactory;
import javax.swing.JDesktopPane;
import javax.swing.JFrame;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;

/**
 *
 * @author Ivana
 */
public class App extends javax.swing.JFrame {

    /**
     * Creates new form App
     */
    public App() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 613, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 429, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                App screen = new App();
                screen.setVisible(true);
                screen.setTitle("Gestor Hoteleria");
                screen.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                screen.setExtendedState(App.MAXIMIZED_BOTH);
                screen.setLocationRelativeTo(null);

                JDesktopPane desktopPane = new JDesktopPane();
                screen.getContentPane().add(desktopPane, BorderLayout.CENTER);
                screen.setContentPane(desktopPane);
                desktopPane.setVisible(true);

                screen.createMenuBar();
            }
        });
    }

    private void createMenuBar() {
        JMenuBar menuBar = new JMenuBar();
        setJMenuBar(menuBar);

        JMenu sistMenu = new JMenu("Sistema Reserva");
        JMenu archivoMenu = new JMenu("Archivo");
        JMenu reservasMenu = new JMenu("Reservas");
        JMenu consultasMenu = new JMenu("Consultas");
        JMenu configMenu = new JMenu("Configuraciones");
        JMenu herMenu = new JMenu("Herramientas");
        JMenu ayudaMenu = new JMenu("Ayuda");
        JMenu salirMenu = new JMenu("Salir");
        menuBar.add(sistMenu);
        menuBar.add(archivoMenu);
        menuBar.add(reservasMenu);
        menuBar.add(consultasMenu);
        menuBar.add(configMenu);
        menuBar.add(herMenu);
        menuBar.add(ayudaMenu);
        menuBar.add(salirMenu);

        JMenuItem habArchivo = new JMenuItem("Habitaciones");
        habArchivo.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                frmHabitacion form = new frmHabitacion();
                desktopPane.add(form);
                form.setVisible(true);
                form.pack();
                form.setLocation(0, 0);
            }
        });
        JMenuItem prodArchivo = new JMenuItem("Productos");
        prodArchivo.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

            }
        });
        archivoMenu.add(habArchivo);
        archivoMenu.add(prodArchivo);

        JMenuItem resconReservas = new JMenuItem("Reservas y Consumos");
        resconReservas.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

            }
        });
        JMenuItem clientesReservas = new JMenuItem("Clientes");
        clientesReservas.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

            }
        });
        JMenuItem pagosReservas = new JMenuItem("Pagos");
        pagosReservas.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

            }
        });
        reservasMenu.add(resconReservas);
        reservasMenu.add(clientesReservas);
        reservasMenu.add(pagosReservas);

        JMenuItem usuaccConfig = new JMenuItem("Usuarios y Accesos");
        usuaccConfig.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

            }
        });
        configMenu.add(usuaccConfig);

        JMenuItem acercaAyuda = new JMenuItem("Acerca de...");
        acercaAyuda.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

            }
        });
        JMenuItem ayudaAyuda = new JMenuItem("Ayuda");
        ayudaAyuda.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

            }
        });
        ayudaMenu.add(acercaAyuda);
        ayudaMenu.add(ayudaAyuda);

        JMenuItem salirSalir = new JMenuItem("Salir");
        salirSalir.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                int opcion = JOptionPane.showConfirmDialog(salirMenu, "¿Desea salir del sistema?", "Salir", JOptionPane.YES_NO_OPTION);
                if (opcion == JOptionPane.YES_OPTION) {
                    dispose();
                    System.exit(0);
                }
            }
        });
        salirMenu.add(salirSalir);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel desktopPane;
    // End of variables declaration//GEN-END:variables
}
